name: Compile LaTeX to PDF
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v2
        with:
          root_file: FinalAssignment.tex
          extra_packages:
            latexmk
            texlive-fonts-recommended
            texlive-latex-extra
            texlive-science
            texlive-pictures

      - name: List files (for debugging)
        run: ls -R

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: FinalAssignment.pdf
          path: FinalAssignment.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: FinalAssignment.pdf